const version = 1;
const concatenate = require("./concatenate.js"),
	flatten = require("./flatten.js"),
	removeDuplicate = require("./remove-duplicate.js"),
	toDromedaryCase = require("./to-dromedary-case.js"),
	toObject = require("./to-object.js"),
	toPascalCase = require("./to-pascal-case.js"),
	toUnderscoreCase = require("./to-underscore-case.js");
module.exports = {
	concat: concatenate,
	concatenate: concatenate,
	ensurePrefix: require("./ensure-prefix.js"),
	ensureSuffix: require("./ensure-suffix.js"),
	flat: flatten,
	flatten: flatten,
	merge: concatenate,
	removeDuplicate: removeDuplicate,
	reverse: require("./reverse.js"),
	split: require("./split.js"),
	toCamelCase: toDromedaryCase,
	toCapitalCase: require("./to-capital-case.js"),
	toDashCase: require("./to-dash-case.js"),
	toDromedaryCase: toDromedaryCase,
	toLowerCamelCase: toDromedaryCase,
	toObj: toObject,
	toObject: toObject,
	toPascalCase: toPascalCase,
	toSnakeCase: toUnderscoreCase,
	toUnderscoreCase: toUnderscoreCase,
	toUpperCamelCase: toPascalCase,
	uniq: removeDuplicate,
	unique: removeDuplicate,
	v: version,
	ver: version,
	version: version
};
